<?php
//
// File generated by ... on the 2017-07-05T11:51:17+0200
// Please do not edit manually
//

/**
 * Classes and menus for itop-profiles-itil (version 2.2.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
//
// List of constant profiles
// - used by the class URP_Profiles at setup (create/update/delete records)
// - used by the addon UserRightsProfile to determine user rights
//
